public class Task1 {
    public static void main(String[] args) {
        //byte, short, int, long,float, double, char, boolean, string
        //сложение, вычитание, умножение, деление, остаток от деления, инкремент и декремент
        byte b=2;
        short st=130;
        int i=11;
        long l=28839;
        float f=2.56f;
        double d=1.458d;
        char ch='a';
        boolean bl=false;
        String s = "I'm still standing";

        System.out.println(b);
        System.out.println(st);
        System.out.println(i);
        System.out.println(l);
        System.out.println(f);
        System.out.println(d);
        System.out.println(ch);
        System.out.println(bl);
        System.out.println(s);

        int sum;
        sum=i+2;
        System.out.println("i + 2 = "+ sum);
        int sum1;
        sum1=st+i;
        System.out.println("i + st = "+ sum1);
        int sum2;
        sum2=b+i;
        System.out.println("i + b = "+ sum2);
        long sum3;
        sum3=l+i;
        System.out.println("l + i = "+ sum3);
        float sum4;
        sum4=f+l;
        System.out.println("f + l = "+ sum4);
        double sum5;
        sum5=d+f;
        System.out.println("f + d = "+ sum5);

        int sub;
        sub=i-2;
        System.out.println("i - 2 = "+ sub);
        int sub1;
        sub1=st-i;
        System.out.println("st - i = "+ sub1);
        int sub2;
        sub2=b-i;
        System.out.println("b - i = "+ sub2);
        long sub3;
        sub3=l-i;
        System.out.println("l - i = "+ sub3);
        float sub4;
        sub4=f-i;
        System.out.println("f - i = "+ sub4);
        double sub5;
        sub5=d-i;
        System.out.println("d - i = "+ sub5);

        int div;
        div=i/2;
        System.out.println("i / 2 = "+ div);
        int rdiv;
        rdiv=i%2;
        System.out.println("i % 2 = "+ rdiv);
        int div1;
        div1=st/2;
        System.out.println("st / 2= "+ div1);
        int rdiv1;
        rdiv1=st%2;
        System.out.println("st % 2= "+ rdiv1);
        int div2;
        div2=b/2;
        System.out.println("b / 2= "+ div2);
        int rdiv2;
        rdiv2=b%2;
        System.out.println("b % 2= "+ rdiv2);
        long div3;
        div3=l/2;
        System.out.println("l / 2= "+ div3);
        long rdiv3;
        rdiv3=l%2;
        System.out.println("l % 2= "+ rdiv3);
        float div4;
        div4=f/2;
        System.out.println("f / 2= "+ div4);
        float rdiv4;
        rdiv4=f%2;
        System.out.println("f % 2= "+ rdiv4);
        double div5;
        div5=d/2;
        System.out.println("d / 2= "+ div5);
        double rdiv5;
        rdiv5=d%2;
        System.out.println("d % 2= "+ rdiv5);

        int mult;
        mult=i*2;
        System.out.println("i * 2= "+ mult);
        int mult1;
        mult1=st*2;
        System.out.println("st * 2= "+ mult1);
        int mult2;
        mult2=b*2;
        System.out.println("b * 2= "+ mult2);
        long mult3;
        mult3=l*2;
        System.out.println("l * 2= "+ mult3);
        float mult4;
        mult4=f*2;
        System.out.println("f * 2= "+ mult4);
        double mult5;
        mult5=d*2;
        System.out.println("d * 2= "+ mult5);

        int inc=i;
        inc++;
        System.out.println("i++= "+ inc);
        int dec=i;
        dec--;
        System.out.println("i--= "+ dec);
        short inc1=st;
        inc1++;
        System.out.println("st++= "+ inc1);
        short dec1=st;
        dec1--;
        System.out.println("st--= "+ dec1);
        byte inc2=b;
        inc2++;
        System.out.println("b++= "+ inc2);
        byte dec2=b;
        dec2--;
        System.out.println("b--= "+ dec2);
        long inc3=l;
        inc3++;
        System.out.println("l++= "+ inc3);
        long dec3=l;
        dec3--;
        System.out.println("l--= "+ dec3);
        float inc4=f;
        inc4++;
        System.out.println("f++= "+ inc4);
        float dec4=f;
        dec4--;
        System.out.println("f--= "+ dec4);
        double inc5=d;
        inc5++;
        System.out.println("d++= "+ inc5);
        double dec5=d;
        dec5--;
        System.out.println("d--= "+ dec5);
    }
}
